"li t1, 9\n\t"
"vsetvli t0, t1, e16, ta, ma\n\t"
"vle16.v v0, (%[p_x])\n\t"
"Loop:\n\t"
"addi t1, t1, -1\n\t"
"lh t2, 0(%[p_x])\n\t"
"vadd.vx v1, v0, t2\n\t"
"vmseq.vx v2, v1, %[target]\n\t"
"vfirst.m t3, v2\n\t"
"bge t3, x0, GetFlag\n\t"
"addi %[p_x], %[p_x], 2\n\t"
"bnez t1, Loop\n\t"
"j End\n\t"
"GetFlag:\n\t"
"addi %[flag], %[flag], 1\n\t"
"End:\n\t"
